development:
  adapter: postgresql
  encoding: unicode
  database: firstapp_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: firstapp_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: firstapp_production
  pool: 5
  username:
  password:
